#Reference https://www.tiuweehan.com/blog/2020-09-10-docker-in-jenkins-in-docker/
version: '3.7'
services:

  docker_in_docker:
    image: docker:dind
    user: root
    privileged: true
    container_name: docker_in_docker
    expose:
      - 2375
    networks:
      - jenkins_docker_in_docker
    environment:
      DOCKER_TLS_CERTDIR: ""

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    container_name: jenkins
    depends_on:
      - docker_in_docker
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins:/var/jenkins_home
      - /usr/bin/docker_in_docker:/usr/bin/docker
    environment:
      DOCKER_HOST: "tcp://docker_in_docker:2375"
    networks:
      - jenkins_docker_in_docker

networks:
  jenkins_docker_in_docker:
    driver: bridge
