version: '3.8'

services:
  dind:
    container_name: jenkins-docker
    image: docker:dind
    user: root
    privileged: true
    restart: unless-stopped
    networks:
      jenkins-network:
        aliases:
          - docker
    volumes:
      - data:/var/jenkins_home
      - certs:/certs/client
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    
  jenkins:
    container_name: jenkins
    depends_on:
      - dind
    image: jenkins/jenkins:lts-jdk11
    user: root
    restart: unless-stopped
    networks:
      - jenkins-network
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - data:/var/jenkins_home
      - certs:/certs/client:ro
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
 
networks:
  jenkins-network:
    name: jenkins
    
volumes:
  data:
    name: jenkins-data
  certs:
    name: jenkins-docker-certs