version: '3.8'
services:

  docker_in_docker:
    image: docker:dind
    user: root
    privileged: true
    container_name: dind
    expose:
      - 2376
    networks:
      jenkins_dind:
    ports:
      - 2376:2376
    environment:
      DOCKER_TLS_CERTDIR: ""

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    container_name: jenkins
    depends_on:
      - docker_in_docker
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
    environment:
      DOCKER_HOST: "tcp://jenkins_dind:2376"
    networks:
      - jenkins_dind

networks:
  jenkins_dind:
    driver: bridge